# Generated by Django 3.1.7 on 2021-12-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32, verbose_name='部門名稱')),
                ('dep_script', models.CharField(max_length=60, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, verbose_name='社團名稱')),
                ('group_script', models.CharField(max_length=60, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='郵箱')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[['1', '男'], ['2', '女']], max_length=1, verbose_name='性別')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='頭像')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='filedir', verbose_name='附件')),
                ('hierarchy', models.CharField(choices=[['1', '總經理'], ['2', '主管'], ['3', '員工']], max_length=1, verbose_name='階級')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.department')),
                ('group', models.ManyToManyField(to='Staff.group')),
            ],
        ),
    ]
